### ISSUE TITLE
Determining Allele-Specific Expression (ASE) using SALSA

### ISSUE THREAD

**Issue by singcell** [p4rkerw/SALSA#2]
Hello,
Thank you for developing this nice tool.
I have single-cell RNA sequencing (scRNA-seq) data from tissues generated by crossing two distinct mouse strains. I am aware of the single nucleotide variants (SNVs) in the parent genomes. I am interested in determining Allele-Specific Expression (ASE) in all expressed genes within my offspring scRNA-seq dataset. What is the best approach for conducting this analysis using SALSA tool? Do you have a pipeline designed for this purpose?

Thank you

**Comment by p4rkerw** [comment]
Thanks for your interest in salsa. Although salsa was not designed with mice in mind, most of the workflow will be applicable to your question. What you need is a vcf of heterozygous variants that differentiate your two mouse strains. Assuming these strains are inbred, you can probably find that info in a public database. You would then take this vcf and quantify allele specific reads for each of your samples after variant aware realignment. If you can’t find genotypes for your strains you could genotype them yourself using a mouse reference and then compile the heterozygous variants. That would be outside the scope of salsa but there are plenty of resources out there you can use for genotyping non human samples. Take a look here https://github.com/igordot/genomics/blob/master/workflows/gatk-mouse-mm10.md for assembling the gatk mouse references
